#!/bin/bash

#autoreconf -i -v --force

CXXFLAGS="-Wall -pthread -D_REENTRANT -I../src -I../../src"
echo $CXXFLAGS
if [[ -z "$@" ]]; then
  if [[ -z "$LOG_LEV" ]]; then
    LOG_LEV=4
  fi
  if [[ -z "$PREFIX" ]]; then
    PREFIX="/usr/local"
  fi
  CXXFLAGS="$CXXFLAGS -I$PREFIX/include -L$PREFIX/lib"
  echo $CXXFLAGS
  export CXXFLAGS
  ./configure --prefix="$PREFIX" --with-log-level=$LOG_LEV --enable-debug
else
  ./configure "$@"
fi

